# https://github.com/morey-tech/argo-cd-app-of-apps-demo/blob/main/app-of-apps.yaml
# https://www.youtube.com/watch?v=2pvGL0zqf9o

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: k8s/apps/app-of-apps-apps
    repoURL: 'https://github.com/renklus/home-network'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
