apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: 'argo-cd'
    targetRevision: '8.1.3'
    helm:
      parameters:
        - name: 'server.service.type'
          value: 'LoadBalancer'        
      valuesObject:
        global:
          image:
            repository: 'quay.io/argoproj/argocd'
            tag: 'v3.0.11@sha256:1cb4ede2fc4a6332c128d9ba29d19e8cb5b76f9260dc47550a4b3b154269ff86'
        server:
          extensions:
            image:
              repository: 'quay.io/argoprojlabs/argocd-extension-installer'
              tag: 'v0.0.8@sha256:e7cb054207620566286fce2d809b4f298a72474e0d8779ffa8ec92c3b630f054'
        dex:
          image:
            repository: 'ghcr.io/dexidp/dex'
            tag: 'v2.43.1@sha256:0881d3c9359b436d585b2061736ce271c100331e073be9178ef405ce5bf09557'
        redis:
          exporter:
            image:
              repository: 'ghcr.io/oliver006/redis_exporter'
              tag: 'v1.74.0@sha256:88862b6fc5004ead3495c16d5ba548b14e898fe6d22e7c5b93bf3df83823a9a5'
          image:
            repository: 'public.ecr.aws/docker/library/redis'
            tag: '8.0.3-alpine@sha256:25c0ae32c6c2301798579f5944af53729766a18eff5660bbef196fc2e6214a9c'
        redis-ha:
          # disabled because renovate cannot dela with it and it is currently unused
          # exporter:
          #   image: 'ghcr.io/oliver006/redis_exporter'
          #   # renovate: datasource=docker depName=ghcr.io/oliver006/redis_exporter
          #   tag: 'v1.73.0@sha256:1a8f5e48b2af0fb02d182be3ddd623e7e39881b6464bdb5bf843b1f6d45ed050'
          image:
            repository: 'public.ecr.aws/docker/library/redis'
            tag: '8.0.3-alpine@sha256:25c0ae32c6c2301798579f5944af53729766a18eff5660bbef196fc2e6214a9c'
        configs:
          cm:
            "users.session.duration": '22h'
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
