apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: 'argo-cd'
    targetRevision: '8.6.0'
    helm:
      parameters:
        - name: 'server.service.type'
          value: 'LoadBalancer'        
      valuesObject:
        global:
          image:
            repository: 'quay.io/argoproj/argocd'
            tag: 'v3.1.8@sha256:19ba7f44cba487c4a0c98ac336327c4df04383dff84f87ea1a578972eb62dd17'
        server:
          extensions:
            image:
              repository: 'quay.io/argoprojlabs/argocd-extension-installer'
              tag: 'v0.0.8@sha256:e7cb054207620566286fce2d809b4f298a72474e0d8779ffa8ec92c3b630f054'
        dex:
          image:
            repository: 'ghcr.io/dexidp/dex'
            tag: 'v2.44.0@sha256:5d0656fce7d453c0e3b2706abf40c0d0ce5b371fb0b73b3cf714d05f35fa5f86'
        redis:
          exporter:
            image:
              repository: 'ghcr.io/oliver006/redis_exporter'
              tag: 'v1.78.0@sha256:043d380adf3b23c9f73a986d820e79491975c104fe0ce6ecb8639a19914654fd'
          image:
            repository: 'public.ecr.aws/docker/library/redis'
            tag: '8.2.2-alpine@sha256:59b6e694653476de2c992937ebe1c64182af4728e54bb49e9b7a6c26614d8933'
        redis-ha:
          # disabled because renovate cannot dela with it and it is currently unused
          # exporter:
          #   image: 'ghcr.io/oliver006/redis_exporter'
          #   # renovate: datasource=docker depName=ghcr.io/oliver006/redis_exporter
          #   tag: 'v1.73.0@sha256:1a8f5e48b2af0fb02d182be3ddd623e7e39881b6464bdb5bf843b1f6d45ed050'
          image:
            repository: 'public.ecr.aws/docker/library/redis'
            tag: '8.2.2-alpine@sha256:59b6e694653476de2c992937ebe1c64182af4728e54bb49e9b7a6c26614d8933'
        configs:
          cm:
            "users.session.duration": '22h'
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
