apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts'
    chart: 'infisical'
    targetRevision: '0.4.2'
    helm:
      parameters:
        - name: 'ingress.nginx.enabled'
          value: 'true'
        - name: 'ingress.hostName'
          value: 'infisical-ingress-nginx-controller.infisical-system.k8s.renklus.ch'
  destination:
    namespace: infisical-system
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# workaround for argcod problem (leave until https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190 is done)
  ignoreDifferences:
  - group: 'apps'
    kind: 'StatefulSet'
    name: 'mongodb'
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts'
    chart: 'secrets-operator'
    targetRevision: '0.3.3'
  destination:
    namespace: infisical-system
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
#---
#apiVersion: v1
#kind: Namespace
#metadata:
#  name: infisical-operator-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-config
  namespace: infisical-system
data:
  hostAPI: 'http://infisical-backend.infisical-system:4000/api'
  # hostAPI: https://app.infisical.com/api # <-- global hostAPI
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: infisicalsecret-sample
  namespace: infisical-system
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: 'infisical-service-token5'
        secretNamespace: infisical-system
      secretsScope:
        envSlug: dev
        secretsPath: "/"
  managedSecretReference:
    secretName: managed-secret5 # <-- the name of kubernetes secret that will be created
    secretNamespace: infisical-system # <-- where the kubernetes secret should be created
---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-service-token5
  namespace: infisical-system
data:
  infisicalToken: 'c3QuNjVhYmUwNTljODUwNmQ1NTljYjY1YjdlLjBjYTFlNjg5MTg3Yzk3ZjNmNTNhMGE0NGM5Y2ZiMDIwLjYyZDRkNTVhNzIzNmMzN2I5ZGQwYjE3MjBmZTdmZWJj' # 'not-populated' (name: service-token-1)
