apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts'
    chart: 'secrets-operator'
    targetRevision: '0.5.0'
    helm:
      valuesObject:
        controllerManager:
          kubeRbacProxy:
            image:
              repository: 'gcr.io/kubebuilder/kube-rbac-proxy'
              tag: 'v0.15.0'
          manager:
            image:
              repository: 'infisical/kubernetes-operator'
              tag: 'v0.5.0'
      parameters:
  destination:
    namespace: infisical-operator-system
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: v1
kind: Namespace
metadata:
  name: infisical-operator-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-config # must not change: https://infisical.com/docs/integrations/platforms/kubernetes
  namespace: infisical-operator-system # must not change
data:
  hostAPI: 'http://infisical-backend.infisical-system:8080/api'
  # hostAPI: https://app.infisical.com/api # <-- global hostAPI
---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-service-token
  namespace: infisical-operator-system
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: infisicalsecret-demo
  namespace: infisical-demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: 'infisical-service-token'
        secretNamespace: 'infisical-operator-system'
      secretsScope:
        envSlug: dev
        secretsPath: "/demo"
  managedSecretReference:
    secretName: managed-infisical-demo-secret # <-- the name of kubernetes secret that will be created
    secretNamespace: infisical-demo # <-- where the kubernetes secret should be created
---
apiVersion: v1
kind: Namespace
metadata:
  name: infisical-demo
---