apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts'
    chart: 'infisical'
    targetRevision: '0.4.2'
    helm:
      parameters:
        - name: 'ingress.nginx.enabled'
          value: 'true'
        - name: 'ingress.hostName'
          value: 'infisical-ingress-nginx-controller.infisical-system.k8s.renklus.ch'
        - name: 'backend.image.tag'
          value: 'v0.43.19'
        - name: 'mongodb.image.tag'
          value: '7.0.6-debian-12-r0'
  destination:
    namespace: infisical-system
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# workaround for argcod problem (leave until https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190 is done)
  ignoreDifferences:
  - group: 'apps'
    kind: 'StatefulSet'
    name: 'mongodb'
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'