apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: 'https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts'
    chart: 'secrets-operator'
    targetRevision: '0.3.3'
    helm:
      parameters:
        - name: 'controllerManager.manager.image.tag'
          value: 'v0.3.3'
        - name: 'controllerManager.kubeRbacProxy.image.tag'
          value: 'v0.15.0'
  destination:
    namespace: infisical-operator-system
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: v1
kind: Namespace
metadata:
  name: infisical-operator-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: infisical-config # must not change: https://infisical.com/docs/integrations/platforms/kubernetes
  namespace: infisical-operator-system # must not change
data:
  hostAPI: 'http://infisical-backend.infisical-system:8080/api'
  # hostAPI: https://app.infisical.com/api # <-- global hostAPI
---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-service-token
  namespace: infisical-operator-system
data:
  infisicalToken: 'empty'
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  # Name of of this InfisicalSecret resource
  name: infisicalsecret-demo
  namespace: infisical-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  resyncInterval: 60
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: 'infisical-demo-service-token'
        secretNamespace: 'infisical-operator-system'
      secretsScope:
        envSlug: dev
        secretsPath: "/demo"
  managedSecretReference:
    secretName: managed-infisical-demo-secret # <-- the name of kubernetes secret that will be created
    secretNamespace: infisical-operator-system # <-- where the kubernetes secret should be created
---
apiVersion: v1
kind: Secret
metadata:
  name: infisical-demo-service-token
  namespace: infisical-operator-system
data:
  infisicalToken: 'c3QuNjVhYmYzODFjYTNjNjFiZWQ4Mzc2Mjk1LmRkYzZhMzg3YjA5ZmVmZWJhNTlkMjM1OWZmMjkxYWMzLmU0MmM2NDdkZTAwNTE1ZmUwMTU1MDUxZDNmMGNkOTY3' # demo-token, no access to real secrets
