kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-demo
  namespace: 'longhorn-demo'
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "2880" # 48 hours in minutes
  fromBackup: ""
  fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-demo-pvc
  namespace: 'longhorn-demo'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-demo
  resources:
    requests:
      storage: 1Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: volume-demo
  namespace: 'longhorn-demo'
spec:
  containers:
  - name: volume-demo
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: volv
    persistentVolumeClaim:
      claimName: longhorn-demo-pvc