# Helm chart changelog: https://github.com/hashicorp/vault-helm/blob/main/CHANGELOG.md
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: 'vault'
    targetRevision: '0.29.1'
    helm:
      valuesObject:
        injector:
          image:
            repository: 'hashicorp/vault-k8s'
            tag: '1.6.1@sha256:0786037b1348957a3cd375b8f3d223bdb7b43be13e1d0f017f1a7a1de39a9f9d'
        agentImage:
          image:
            repository: 'hashicorp/vault'
            tag: '1.18.3@sha256:8f1ba670da547c6af67be55609bd285c3ee3d8b73f88021adbfc43c82ca409e8'
        server:
          image:
            repository: 'hashicorp/vault'
            tag: '1.18.3@sha256:8f1ba670da547c6af67be55609bd285c3ee3d8b73f88021adbfc43c82ca409e8'
        csi:
          image:
            repository: 'hashicorp/vault-csi-provider'
            tag: '1.5.0@sha256:1d27e109f69f410e6db0f2681c8367e3939ba6f103c4f9206e56209e37dba6aa'
          agent:
            image:
              repository: 'hashicorp/vault'
              tag: '1.18.3@sha256:8f1ba670da547c6af67be55609bd285c3ee3d8b73f88021adbfc43c82ca409e8'
        ui:
          loadBalancerSourceRanges:
            - 10.0.0.0/8
      parameters:
        - name: 'global.namespace'
          value: 'vault-system'
        - name: 'global.namespace'
          value: 'vault-system'
        # - name: 'server.service.type'
        #   value: 'LoadBalancer'
        - name: 'ui.enabled'
          value: 'true'
        - name: 'ui.serviceType'
          value: 'LoadBalancer'
        - name: 'ui.serviceNodePort'
          value: 'null'
  destination:
    namespace: 'vault-system'
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# workaround for argcod problem (leave until https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190 is done)
  ignoreDifferences:
  - group: 'apps'
    kind: 'StatefulSet'
    name: 'mongodb'
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'