apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.6/manifests/ha/install.yaml
- https://raw.githubusercontent.com/renklus/home-network/main/k8s/apps/app-of-infrastructure-apps/argo-initial.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        namespace: argocd
        name: argocd-server
      spec:
        type: "LoadBalancer"
    target:
      kind: "Service"
      labelSelector: "app.kubernetes.io/name=argocd-server"
