apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: 'immich'
  annotations:
    # Keep the PVC when the immich app is removed.
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs
  resources:
    requests:
      storage: 500Gi