apiVersion: v1
kind: Namespace
metadata:
  name: immich
  annotations:
    # Keep the namespace when the immich app is delete so the PVC is not removed.
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
