# from https://github.com/immich-app/immich-charts/blob/main/local/cloudnative-pg.yaml as recommended by https://github.com/immich-app/immich-charts/blob/main/README.md
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  instances: 1

  storage:
    storageClass: truenas-nfs-hard
    size: 1Gi

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16.9-0.4.3

  postgresql:
    shared_preload_libraries:
      - "vchord.so"

  bootstrap:
    initdb:
      # TODO: Use managed extensions (pg 18)
      postInitApplicationSQL:
        # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
        - CREATE EXTENSION vchord CASCADE;
        - CREATE EXTENSION earthdistance CASCADE;