# When making this config secure and automated then consult: https://gist.github.com/janeczku/b16154194f7f03f772645303af8e9f80 (a copy is in this repo as /docs/k8s-rancher-cluster-connection.md)
# currently: take bearer token and server URL from kubeconfig (downloaded from Rancher UI)
# maybe also useful: https://web.archive.org/web/20251214083235/https://mgior.com/posts/k3s-argocd/

apiVersion: v1
kind: Secret
metadata:
  # name of this resource
  name: argo-cluster-prod
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  # name how applications reference this cluster
  name: prod
  server: https://rancher.cattle-system.svc.cluster.local/k8s/clusters/c-m-jglqxkzx
  # the argo server cannot resolve this URL to an IP:  server: https://rancher.ingress.rancher.k8s.renklus.ch/k8s/clusters/c-m-xxxxxxxx
  config: |
    {
      "bearerToken": "kubeconfig-user-4dcn6sxcxq:7mw9vwv6q62d4j5z5rn8qb587xjpzpkp2bzv67xb95svnx5x5hgnjk",
      "tlsClientConfig": {
        "insecure": true
      }
    }