apiVersion: provisioning.cattle.io/v1
kind: Cluster
metadata:
  name: sub-cluster
  labels:
    #  key: string
  namespace: fleet-default
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    # argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true # maybe this is not needed if it is in a syncwave after rancher main chart
spec:
  kubernetesVersion: 'v1.34.5+k3s1'
  rkeConfig:
    machineGlobalConfig:
      disable:
        - servicelb
        - traefik
        - local-storage
      etcd-expose-metrics: true
      disable-etcd: false
      tls-san:
        - k8s02d.dev.renklus.ch
        - prod.k8s.renklus.ch
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: sub-cluster-kubeconfig
#   namespace: argocd
# type: Opaque
# data:
#   kubeconfig: |
#     apiVersion: v1
#     clusters:
#     - cluster:
#         certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
#           VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
#           kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
#           GMzTWpJNQpNREkwTVRBZUZ3MHlOakF5TWpneE16VXdOREZhRncwek5qQXlNall4TXpVd05ERmFNR\
#           Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
#           1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56Y3lNamt3TWpReE1Ga3dFd1lIS29aSXpqMENBU\
#           VlJS29aSXpqMERBUWNEUWdBRXJESEdYYlBWT3dZcApmSzFMWUV5OW41bkM4S25kVEIvT2NBNzl0Z\
#           mJkdHc1cUFVcjluSzNkZXpJK0Y4cU5UeXpkL1FNSXlTcU9yUU5rCmdxa2ZQOGJDZjZOQ01FQXdEZ\
#           1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGQ\
#           XMrZndPSlE0WkQvMFFNQS8rOFFyWG03T1A2TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFERQpKU\
#           VpBcEdOa3hmM0xNS09qVTAyaGkwUkU2dUlWVXdxRTJyRDFpNVVlVkFJZ1piWU5xWWFaVk8rWG03e\
#           TgwMjdCCmNEOS9LZE1HUEdGNFhSMEd0RGdKVThBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"
#         server: https://rancher.ingress.rancher.k8s.renklus.ch/k8s/clusters/c-m-mllxsfhr
#       name: sub-cluster
#     contexts:
#     - context:
#         cluster: sub-cluster
#         user: admin
#       name: sub-cluster
#     current-context: sub-cluster
#     kind: Config
#     preferences: {}
#     users:
#     - name: admin
#       user:
#         token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlQzc21EYmNtVjBQTmZJUXJYZksySEZqcWphVDNvbzY0TGs5LVNxY0todmcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJjYXR0bGUtc3lzdGVtIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImNhdHRsZS10b2tlbi13cmxmOCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJjYXR0bGUiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI4N2I3ZTcxNy01NDUwLTRiNGEtODJhZS01YjNmNzZjODI1Y2EiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6Y2F0dGxlLXN5c3RlbTpjYXR0bGUifQ.Jn3bQgfOa9NfdOmatyalsFUx96RbwxJasWg4cn1CbvRa48wGNxPPOPez5ruMECN-nhpkuL1BxnzM4Jv2kST6_2NcddMmU96YOLN9Dgv2TE5jgnE_yN6qX_FLnat8RrBr85VMPOxb85gcBv2VzDuA9giTxwoIEnId05q7mqF-A0DkE4VHBuX3cbPnWh-gRpb9Xfd_SsNOw5PbJzX1BEi_RY2FSpZa-aEUvKep_x1T81hLrWltTXQJ47Llb5m3DkB9oT9sSFz7Th2lbciQlNVtsy5dRIHiK-zO8qnTHqnl01m9F0lRlNZnaarj1iDYiz2A37WUXhMUv1TUklVc3Vqslglukas@lukas-5950x
# ---
# apiVersion: argoproj.io/v1alpha1
# kind: Cluster
# metadata:
#   name: sub-cluster
#   namespace: argocd
# spec:
#   server: https://rancher.ingress.rancher.k8s.renklus.ch/k8s/clusters/c-m-mllxsfhr
#   name: sub-cluster
#   kubeconfigSecret:
#     name: sub-cluster-kubeconfig
#     key: kubeconfig