apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/renklus/home-network/master/k8s/apps/k8s-infra/argo/argo-custom.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/2.10.2/manifests/install.yaml