apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages'
    chart: 'plex-media-server'
    targetRevision: '0.3.0'
    helm:
      valuesObject: # parametrization with valuesObject needed for renovate bot to detect image versions
        image:
          tag: '1.40.0.7998-c29d4c0c8'
          repository: 'plexinc/pms-docker' # repository definition needed for renovate bot to detect latest version
          registry: 'index.docker.io' # registry definition only needed if something else than docker
        initContainer:
          image:
            tag: '3.21.3@sha256:a8560b36e8b8210634f77d9f7f9efd7ffa463e380b75e2e74aff4511df3ef88c'
            repository: 'alpine'
            registry: 'index.docker.io'
        rclone:
          image:
            tag: '1.66.0'
            repository: 'rclone/rclone'
            registry: 'index.docker.io'
      parameters:
        - name: 'service.type'
          value: 'LoadBalancer'
        - name: 'service.port'
          value: '32400'
        - name: 'pms.configStorage'
          value: '10Gi'
  destination:
    namespace: plex-staging
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# workaround for argcod problem (leave until https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190 is done)
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'
