# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: decoy-pool
#   namespace: metallb-system
# spec:
#   addresses:
#   - 10.1.0.201-10.1.0.209
# ---
# 172.22.47.255/20
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  addresses:
  - 10.1.0.210-10.1.0.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default-pool-advertisement
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ipAddressPools:
  - default-pool
