apiVersion: v1
kind: Namespace
metadata:
  name: adguard
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adguard
  namespace: adguard
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  sources:
  - path: k8s/apps/app-of-apps-apps/adguard
    repoURL: 'https://github.com/renklus/home-network'
    targetRevision: HEAD
  destination:
    namespace: adguard
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true