apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-staging
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: '0.2.1'
    helm:
      valueFiles:
        - $values/k8s/apps/app-of-apps-apps/plex-staging-values.yaml
      parameters:
        - name: 'service.type'
          value: 'LoadBalancer'
        - name: 'service.port'
          value: '32400'
        - name: 'pms.configStorage'
          value: '10Gi'
  - repoURL: 'https://github.com/renklus/home-network.git'
    targetRevision: HEAD
    ref: values
  destination:
    namespace: plex-staging
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# workaround for argcod problem (leave until https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190 is done)
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'
