apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex-test
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages
    chart: plex-media-server
    targetRevision: '0.1.8'
    helm:
      parameters:
        - name: service.type
          value: 'LoadBalancer'
        - name: service.port
          value: '32400'
  destination:
    namespace: plex-test-namespace
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'
