apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plex
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages'
    chart: 'plex-media-server'
    targetRevision: '0.3.0'
    helm:
      valuesObject:
        image:
          tag: '1.40.0.7998-c29d4c0c8'
          repository: 'plexinc/pms-docker'
          registry: 'index.docker.io'
        initContainer:
          image:
            tag: '3.19.1'
            repository: 'alpine'
            registry: 'index.docker.io'
        rclone:
          image:
            tag: '1.66.0'
            repository: 'rclone/rclone'
            registry: 'index.docker.io'
      parameters:
        - name: 'service.type'
          value: 'LoadBalancer'
        - name: 'service.port'
          value: '32400'
        - name: 'rclone.configSecret'
          value: 'backblaze-readwrite'
  destination:
    namespace: plex
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# workaround for argcod problem (leave until https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190 is done)
  ignoreDifferences:
  - group: apps
    kind: StatefulSet
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'