apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: 'prometheus'
    targetRevision: '28.9.0'
    helm:
      parameters:
        - name: 'server.service.type'
          value: 'LoadBalancer'
        - name: 'server.persistentVolume.storageClass'
          value: 'truenas-nfs-hard'
        - name: 'alertmanager.persistence.storageClass'
          value: 'truenas-nfs-hard'
      valuesObject:
        configmapReload:
          prometheus:
            image:
              repository: 'quay.io/prometheus-operator/prometheus-config-reloader'
              tag: 'v0.89.0@sha256:cb4ac6a56555bef0e202bec11e367dfe07ffb241cf4d30566b12b864692607a8'
        server:
          image:
            repository: 'quay.io/prometheus/prometheus'
            # if not set appVersion field from Chart.yaml is used
            tag: '@sha256:1f0f50f06acaceb0f5670d2c8a658a599affe7b0d8e78b898c1035653849a702'
  destination:
    namespace: prometheus
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# ---
# #https://pete8s.medium.com/installing-prometheus-on-kubernetes-with-argocd-a4e99580543d
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 13.7.2
#     chart: kube-prometheus-stack
# destination:
#   server: https://kubernetes.default.svc
#   namespace: prometheus