apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssl-reverse-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: 'nginx'
    targetRevision: '18.2.3'
  destination:
    name: 'in-cluster'
    namespace: 'ssl-reverse-proxy'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
