apiVersion: v1
kind: ConfigMap
metadata:
  name: serverblock
  namespace: 'ssl-reverse-proxy'
data:
  serverBlock: |
    server { 
      listen 80; 
      server_name fws07l.dev.renklus.ch;
      location / {
        return 444;
      }
      location /.well-known {
        resolver 10.1.0.1;
        set $routerUrl $scheme://$host:8080/$request_uri;
        proxy_pass $routerUrl;
      }
    }
    server {
      listen 80;
      server_name anydevicename.dev.renklus.ch;
      location / {
        return 444;
      }
      location /.well-known {
        resolver 10.1.0.1;
        proxy_pass $scheme://$host$request_uri;
      }
    }
    server {
      listen 80;
      server_name "";
      return 444;
    }
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssl-reverse-proxy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    chart: 'nginx'
    targetRevision: '18.2.3'
    helm:
      valuesObject:
        image:
          tag: '1.27.2'
          repository: 'bitnami/nginx'
          registry: 'docker.io'
  destination:
    name: 'in-cluster'
    namespace: 'ssl-reverse-proxy'
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
