# https://github.com/morey-tech/argo-cd-app-of-apps-demo/blob/main/app-of-apps.yaml
# https://www.youtube.com/watch?v=2pvGL0zqf9o
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    # prod argocd controller app not delete all prod resources when it is deleted by accident
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: k8s-prod/apps
    repoURL: 'https://github.com/renklus/home-network'
    targetRevision: HEAD
  project: rancher-cluster
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true