apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: 'argo-cd'
    targetRevision: '9.4.2'
    helm:
      parameters:
        - name: 'server.service.type'
          value: 'LoadBalancer'
      valuesObject:
        global:
          image:
            repository: 'quay.io/argoproj/argocd'
            tag: 'v3.3.0' # Keep this one as it auto-shows good changenotes in renovate.
        # do not set these explicitly. The helm chart will update it when it is time.
        # server:
        #   extensions:
        #     image:
        #       repository: 'quay.io/argoprojlabs/argocd-extension-installer'
        #       tag: 'v0.0.9'
        # dex:
        #   image:
        #     repository: 'ghcr.io/dexidp/dex'
        #     tag: 'v2.43.0'
        # redis:
        #   exporter:
        #     image:
        #       repository: 'ghcr.io/oliver006/redis_exporter'
        #       tag: 'v1.81.0'
        #   image:
        #     repository: 'public.ecr.aws/docker/library/redis'
        #     tag: '8.2.3-alpine'
        # redis-ha:
        #   # disabled because renovate cannot dela with it and it is currently unused
        #   # exporter:
        #   #   image: 'ghcr.io/oliver006/redis_exporter'
        #   #   # renovate: datasource=docker depName=ghcr.io/oliver006/redis_exporter
        #   #   tag: 'v1.73.0@sha256:1a8f5e48b2af0fb02d182be3ddd623e7e39881b6464bdb5bf843b1f6d45ed050'
        #   image:
        #     repository: 'public.ecr.aws/docker/library/redis'
        #     tag: '8.2.3-alpine'
        configs:
          cm:
            "users.session.duration": '22h'
          params:
            "create": 'true'
            # required for https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190
            # see also Server-Side Diff: https://argo-cd.readthedocs.io/en/stable/user-guide/diff-strategies/
            "controller.diff.server.side": 'true'
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

# Manage sub-clusters: https://gist.github.com/janeczku/b16154194f7f03f772645303af8e9f80