apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io # might benefit from background delete: https://github.com/argoproj/argo-cd/issues/5724#issuecomment-1041586611
spec:
  project: 'default'
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: '1.19.3'
    helm:
      parameters:
        - name: 'crds.enabled'
          value: 'true'
        # no need to specify image tags because the default is same as chart version. Dependabot can just update the chart
  destination:
    namespace: cert-manager # has to be exactly this namespace for rancher to find it
    name: in-cluster
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true