apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: haproxy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sources:
  - repoURL: https://haproxytech.github.io/helm-charts
    chart: haproxy
    targetRevision: '1.30.2'
    helm:
      valuesObject:
        image:
          repository: 'docker.io/haproxytech/haproxy-alpine'
          tag: '3.4.5@sha256:907ff654f5bd740f94ff190f217c6fdc5f856fdd883f5c127ea8de9b2ce0df07'
        config: |
          global
            log stdout format raw local0
            maxconn 20

          defaults
            mode http
            log global
            # option httplog
            timeout connect 4s
            timeout client 4s
            timeout server 4s

          resolvers dns
            parse-resolv-conf
            accepted_payload_size 8192
         
          frontend stats
            mode http
            bind :1024
            stats enable
            stats refresh 10s
            stats uri /
            stats show-modules

          frontend incoming-http
            bind [::]:8000 v4v6
            acl allowed-path path_beg /.well-known/acme-challenge/
            http-request return status 404 content-type text/plain lf-string "not found" unless allowed-path
            # acl host-vrt01p hdr(host),lower -i vrt01p.dev.renklus.ch
            # use_backend vrt01p if host-vrt01p
            use_backend vrt01p if { req.hdr(host) -i vrt01p.dev.renklus.ch }
            use_backend app07d if { req.hdr(host) -i app07d.dev.renklus.ch }
            use_backend app01l if { req.hdr(host) -i app01l.dev.renklus.ch }
            use_backend app02l if { req.hdr(host) -i app02l.dev.renklus.ch }
            use_backend testing if { req.hdr(host) -i haproxy.haproxy.rancher.k8s.renklus.ch:8000 }
            default_backend rejected

          backend rejected
            http-request return status 404 content-type text/plain lf-string "not-found"

          backend vrt01p
            server vrt01p vrt01p.dev.renklus.ch:80 resolvers dns init-addr last,libc,none

          backend app07d
            server app07d app07d.dev.renklus.ch:80 resolvers dns init-addr last,libc,none

          backend testing
            server testing app07d.dev.renklus.ch:80 resolvers dns init-addr last,libc,none

          backend app01l
            server app01l app01l.dev.renklus.ch:80 resolvers dns init-addr last,libc,none

          backend app02l
            server app02l app02l.dev.renklus.ch:80 resolvers dns init-addr last,libc,none

        service:
          type: LoadBalancer
          enablePorts:
            http: true
            https: false
            quic: false
            stat: true
            admin: false
        containerPorts:
          http: 8000
          stat: 1024
  - path: k8s-rancher/apps/haproxy
    repoURL: 'https://github.com/renklus/home-network'
    targetRevision: HEAD
  project: rancher-cluster
  destination:
    namespace: haproxy
    name: in-cluster
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true