apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: del-tmp
  namespace: argocd
  # annotations:
  #   argocd.argoproj.io/sync-wave: "4"
  finalizers:
  - resources-finalizer.argocd.argoproj.io # means argocd will delete all resources deployed by this application when the application is deleted
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 21.0.0
    chart: prometheus
  destination:
    name: prod
    namespace: del-tmp
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true