apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-infrastructure
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: k8s/apps/app-of-infrastructure-apps
    repoURL: 'https://github.com/renklus/home-network'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
