apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher-clusters
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5" # after rancher
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: k8s-rancher/app-of-infrastructure-apps/rancher
    repoURL: 'https://github.com/renklus/home-network'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true