# Helm chart changelog: https://github.com/hashicorp/vault-helm/blob/main/CHANGELOG.md
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hashicorp-vault-secrets-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: 'vault-secrets-operator'
    targetRevision: '0.6.0'
    helm:
      valuesObject:
        kubeRbacProxy:
          image:
            repository: 'gcr.io/kubebuilder/kube-rbac-proxy'
            tag: 'v0.16.0@sha256:771a9a173e033a3ad8b46f5c00a7036eaa88c8d8d1fbd89217325168998113ea'
        manager:
          image:
            repository: 'hashicorp/vault-secrets-operator'
            tag: '0.6.0@sha256:291286541d7c3052674021003b907c17e7019b9f499790b0859e1fb8442ffc93'
  destination:
    namespace: 'hashicorp-vault-operator-system'
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# Should not be necessary anymore because argocd is globally configured with Server-Side Diff
# # workaround for argcod problem (leave until https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190 is done)
#   ignoreDifferences:
#   - group: 'apps'
#     kind: 'StatefulSet'
#     name: 'mongodb'
#     jqPathExpressions:
#       - '.spec.volumeClaimTemplates[]?'