# Helm chart changelog: https://github.com/hashicorp/vault-helm/blob/main/CHANGELOG.md
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: 'default'
  source:
    repoURL: 'https://helm.releases.hashicorp.com'
    chart: 'vault'
    targetRevision: '0.28.0'
    helm:
      valuesObject:
        injector:
          image:
            repository: 'hashicorp/vault-k8s'
            tag: '1.6.2@sha256:103a2d817a7474a8b678d830b0d6ed2d570cc878e4bc8c146d8d35ec436a8d49'
        agentImage:
          image:
            repository: 'hashicorp/vault'
            tag: '1.19.4@sha256:b5f675b0bf681568cd7354c697fe4ce953024312d6d23ee7216deda60c192bad'
        server:
          image:
            repository: 'hashicorp/vault'
            tag: '1.19.4@sha256:b5f675b0bf681568cd7354c697fe4ce953024312d6d23ee7216deda60c192bad'
        csi:
          image:
            repository: 'hashicorp/vault-csi-provider'
            tag: '1.5.0@sha256:1d27e109f69f410e6db0f2681c8367e3939ba6f103c4f9206e56209e37dba6aa'
          agent:
            image:
              repository: 'hashicorp/vault'
              tag: '1.19.4@sha256:b5f675b0bf681568cd7354c697fe4ce953024312d6d23ee7216deda60c192bad'
        ui:
          loadBalancerSourceRanges:
            - 10.0.0.0/8
      parameters:
        - name: 'global.namespace'
          value: 'vault-system'
        - name: 'global.namespace'
          value: 'vault-system'
        # - name: 'server.service.type'
        #   value: 'LoadBalancer'
        - name: 'ui.enabled'
          value: 'true'
        - name: 'ui.serviceType'
          value: 'LoadBalancer'
        - name: 'ui.serviceNodePort'
          value: 'null'
  destination:
    namespace: 'vault-system'
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
# workaround for argcod problem (leave until https://github.com/argoproj/argo-cd/issues/11143#issuecomment-1664144190 is done)
  ignoreDifferences:
  - group: 'apps'
    kind: 'StatefulSet'
    name: 'mongodb'
    jqPathExpressions:
      - '.spec.volumeClaimTemplates[]?'