apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- argo-initial.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/refs/heads/master/manifests/ha/install.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        namespace: argocd
        name: argocd-server
      spec:
        type: "LoadBalancer"
    target:
      kind: "Service"
      labelSelector: "app.kubernetes.io/name=argocd-server"
