# built with `docker build . -t ghcr.io/renklus/paperless-ngx-backup:v9`
# published with `docker push ghcr.io/renklus/paperless-ngx-backup:v9`

FROM ghcr.io/paperless-ngx/paperless-ngx:2.20.9@sha256:1d99ede700ffdf7aa44899b5fee29c8c279f175769b6cb295e91e9f15772728e
LABEL org.opencontainers.image.source=https://github.com/renklus/home-network

COPY ./rootfs /