# built with `docker build . -t ghcr.io/renklus/paperless-ngx-backup:v9`
# published with `docker push ghcr.io/renklus/paperless-ngx-backup:v9`

FROM paperless-ngx/paperless-ngx:2.20.3
LABEL org.opencontainers.image.source=https://github.com/renklus/home-network

COPY ./rootfs /