apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: 'immich'
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-nfs-hard
  resources:
    requests:
      storage: 500Gi