apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://raw.githubusercontent.com/renklus/home-network/master/k8s-dmz/apps/k8s-infra/argo/argo-custom.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.6/manifests/install.yaml
